### ISSUE TITLE
Can i get a Blendshape weight and put it in an Animator parameter? 

### ISSUE THREAD

**Issue by Jos158v** [emilianavt/VSeeFaceSDK#21]
I mean, when Right eye is 50% closed put a value of 50 on an integer parameter for animations and blendtrees...
A more reliable way to do this:
![image](https://user-images.githubusercontent.com/58456664/179674000-96439e2b-077a-4c5c-965d-b68a67ef8833.png)

**Comment by emilianavt** [comment]
Just set the value being set in the animation to 1 for the whole duration. The animation is applied weighted by the blendshape weight, so the 1 will end up being the value of the blendshape. The current animation probably does not do what it is supposed to do. However, you will need to use a float animator parameter instead of an integer one, since the value will be from 0 to 1 rather than from 0 to 100.

**Comment by Jos158v** [comment]
Thank you so much :)
