### ISSUE TITLE
Adding props using VSF_Animations not working

### ISSUE THREAD

**Issue by NothingMuch123** [emilianavt/VSeeFaceSDK#23]
__Environment__
- Unity 2019.4.31f1
- UniVRM 0.98.0
- VSF_SDK v1.13.38

__Steps to add new expression__
1. Import vrm
2. Drag generated vrm prefab into scene
3. Add prop onto vrm model
4. Create animation clip with only 1 frame (Position and scale of prop changes only)
5. Add new blendshape
6. Attach VSF_Animations component to vrm model root gameobject
7. Set blendshape and animation clip in VSF_Animations component
8. Export vrm model gameobject to vrm file

__Results__
- Prop is visible in VSeeFace
- Prop position and scale does not change when using shortcut key to toggle expression

Tutorial followed: https://youtu.be/Jz81NOeJ92A?t=115

**Comment by emilianavt** [comment]
It's hard to tell what the issue could be in this specific case. Generally, rather than changing the scale to show/hide a prop, I would recommend disabling the object and then enabling it with an animation as shown in [this](https://www.youtube.com/watch?v=FCaUKjC1EGY) tutorial. I would also recommend using two frames in the animation so that it has a start and end, although this may not matter much, and making sure that it is set to loop.

I would also recommend using UniVRM 0.89, especially with VSFAvatar format, since that is the version that VSeeFace uses.

**Comment by NothingMuch123** [comment]
Thanks for the reply, I'll try out some of the suggestions you mentioned and get back to you again if it works or not.

**Comment by NothingMuch123** [comment]
Thanks for the link to the tutorial. Turns out I was exporting the model wrongly. I was exporting to vrm with univrm instead of vsfavatar using the sdk. Will be closing this issue.
