### ISSUE TITLE
VSeeFaceSDK window not showing up in Unity.

### ISSUE THREAD

**Issue by MonolithCK** [emilianavt/VSeeFaceSDK#6]
So, i recently started using new project i made for the avatar. However, no matter what I do, the VSF SDK does not show up for me to export my model with Poi shaders. I dont know why this is occuring. It is the correct unity version and im using .78 vers of UniVRM (the latest one does not work with this vers of unity)
![image](https://user-images.githubusercontent.com/89355600/130365718-05a26c39-deda-4e36-ab60-ba913ae9147c.png)

**Comment by emilianavt** [comment]
Hi, this usually happens when there is a compiler error from some asset in the project. If you switch the bottom pane to "Console", you will probably be able to find errors marked in red, indicating which asset is causing the issue.

Also, the currently supported version of UniVRM is 0.66, which was the stable version until the release of 0.80.
